spring.application.name=booking

# Use Environment Variables with local fallbacks
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mehandi_booking}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:|manam| |yasu|}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Let Hibernate detect the dialect automatically
server.port=${PORT:8080}